### ISSUE TITLE
Add priority levels for the pixels to be drawn

### ISSUE THREAD

**Issue by torfbolt** [stake-house/DecentralizedGraffitiDrawing#8]
To avoid drawing your image into contested space, it might be helpful to not just randomly select pixels to be drawn, but instead draw the outline of the image first. This way, other users of the wall can see early on if an area is in use by someone else.

The way this could work is:
1. Change the random sampling algorithm of the graffiti file generator: Group pixels by priority group number, starting from 0. Skip groups that are completely drawn. Do random sampling only within the first subgroup of pixels that is not yet fully drawn.
2. When generating the json file, group the pixels into multiple groups
3. Group 0 would be the corner pixels, if those are non-transparent
4. Group 1 are the edge pixels of the image, if they are non-transparent
5. Group 2 are the contour pixels of the actual non-transparent content, i.e. do an erode-grow to identify them
6. Group 3 would be all other pixels

**Comment by RomiRand** [comment]
Thanks for the issue! We've added pixel priority support. The details differ a bit from your suggestion: There's a variable amount of priority levels which can be defined by the user. Selecting and grouping them from hand is probably faster though - turns out edge detection can be a bit annoying for extreme low-res images which most users draw, so the viewer got even more messy. Fortunately it's rarely used :sweat_smile:

We can reopen if the changes don't fulfill your needs yet.
